name: starter_template
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  dart_appwrite: ^10.0.0

dev_dependencies:
  build_runner: ^2.4.6
  mockito: ^5.4.2
  test: ^1.24.9
  very_good_analysis: ^5.1.0
